# Permalinks
permalink:           pretty

# Setup
title:               Chaos Reduction Squad
tagline:
url:                 https://chaosreduction.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jordan Bibla
  url:               https://twitter.com/jbibla
  email:             jbibla@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jolesbi/cr-squad

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
