url: "http://cephalopod.equipment" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Cephalopod Equipment Corp." # the name of your site, e.g. ACME Corp.
